spring.application.name=project-service
server.port=8083

spring.data.mongodb.uri=mongodb+srv://marwenjammazi171_db:marwenjammazi171@cluster0.izxexhd.mongodb.net/devops_project_db?retryWrites=true&w=majority&appName=Cluster0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=DEVOPS_CONTROL_CENTER_SUPER_SECRET_KEY_2026_CHANGE_IN_PRODUCTION_1234567890_ABCDEFG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.file.name=../../../logs/projects/project-service.log
